-- timestamp2 for ms precision
CREATE TABLE T_MINIPAS_SYNC (
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    IDNUMMER VARCHAR(200) NOT NULL,
    SKEMAOPDAT_MS BIGINT,
    SOURCE_TABLE_NAME VARCHAR(50)
)

CREATE TABLE MinipasImporterStatus (
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    Type VARCHAR(20),
    StartTime DATETIME NOT NULL,
    EndTime DATETIME,
    Outcome VARCHAR(20),
    ErrorMessage VARCHAR(200)
)