CREATE TABLE IF NOT EXISTS T_MINIPAS_SYNC (
    ID BIGINT(15) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    IDNUMMER VARCHAR(200) NOT NULL,
    SKEMAOPDAT_MS BIGINT,
    SOURCE_TABLE_NAME VARCHAR(255)
) ENGINE=InnoDB COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS MinipasImporterStatus (
    Id BIGINT(15) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Type VARCHAR(20),
    StartTime DATETIME NOT NULL,
    EndTime DATETIME,
    Outcome VARCHAR(20),
    ErrorMessage VARCHAR(200),

    INDEX (StartTime)
) ENGINE=InnoDB COLLATE=utf8_bin;