--db2
-- T_MINIPAS_SYNC:
-- ID bigint identity/AUTO_INCREMENT
-- IDNUMMER VARCHAR(255) // IDNUMMER from T_ADM20XX
-- SKEMAOPDAT Date of latest creation/update of the IDNUMMER row
-- SOURCE_TABLE_NAME VARCHAR(255) // e.g. T_ADM2013
CREATE TABLE T_MINIPAS_UGL_STATUS (
 K_ID SMALLINT,
 C_VERSION CHAR,
 C_SYSTEM VARCHAR(255),
 D_STARTDATETIME TIMESTAMP,
 D_ENDDATETIME TIMESTAMP,
 V_RETURNCODE INTEGER,
 C_LOGFILE VARCHAR(255),
 C_USER VARCHAR(255),
 C_HOSTNAME VARCHAR(255),
 TS_OPDATDTO TIMESTAMP
)

